apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: arbaj13/appserver
        ports:
        - containerPort: 8080
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh','-c','untill nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        - name: init-vpromq01
          image: busybox
          command: ['sh','-c','untill nslookup vpromq01; do echo waiting for vpromq01; sleep 2; done;']

        
